stages:
  - test
  - build
  - deploy

job1:
  stage: test
  tags:
    - docker
  script:
    - echo "I am job1"

job2:
  stage: build
  tags:
    - docker
  script:
    - echo "I am job2"

job3:
  stage: deploy
  tags:
    - docker
  script:
    - echo "I am job3"