image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

before_script:
  - docker build -t joel/countingdown -f Dockerfile .

job1:
  stage: test
  tags:
    - docker
  script:
    - docker run joel/countingdown npm run test

job2:
  stage: deploy
  tags:
    - docker
  script:
    - echo "I am job3"