stages:
  - build
  - test
  - deploy

job1:
  stage: build
  tags:
    - docker
  script:
    - docker build -t joel/countingdown -f Dockerfile .

job2:
  stage: test
  tags:
    - docker
  script:
    - docker run joel/countingdown npm run test

job3:
  stage: deploy
  tags:
    - docker
  script:
    - echo "I am job3"