image: docker:18

services:
  - docker:dind

stages:
  - test
  - deploy

job1:
  stage: test
  tags:
    - docker
  script:
    - docker build -t registry.gitlab.com/loophone/countingdown -f Dockerfile .
    - docker run joel/countingdown npm run test
    - docker login registry.gitlab.com -u joel -p $PERSONAL_ACCESS_TOKEN
    - docker push registry.gitlab.com/loophone/countingdown
    - docker logout

job2:
  stage: deploy
  tags:
    - docker
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - docker -H ssh://deploy@173.242.127.125:28960 build -t joel/countingdown -f Dockerfile .
  when: manual
    