image: docker:18

services:
  - docker:dind

stages:
  - test
  - deploy

job1:
  stage: test
  tags:
    - docker
  script:
    - docker build -t joel/countingdown -f Dockerfile .
    - docker run joel/countingdown npm run test

job2:
  stage: deploy
  tags:
    - docker
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - docker -H ssh://deploy@173.242.127.125:28960 build -t joel/countingdown -f Dockerfile .