image: docker:18

services:
  - docker:dind

stages:
  - test
  - deploy
variables:
  DOCKER_HOST: ssh://deploy@173.242.127.125:28960 
  
job1:
  stage: test
  tags:
    - docker
  script:
    - docker build -t joel/countingdown -f Dockerfile .
    - docker run joel/countingdown npm run test

job2:
  stage: deploy
  tags:
    - docker
  script:
    - docker -H $DOCKER_HOST build -t joel/countingdown -f Dockerfile .