image: docker:18

services:
  - docker:dind

stages:
  - test
  - deploy

job1:
  stage: test
  tags:
    - docker
  script:
    - docker build -t registry.gitlab.com/loophone/countingdown -f Dockerfile .
    - docker run registry.gitlab.com/loophone/countingdown npm run test
    - docker login registry.gitlab.com -u joel -p $PERSONAL_ACCESS_TOKEN
    - docker push registry.gitlab.com/loophone/countingdown
    - docker logout

job2:
  stage: deploy
  tags:
    - docker
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - ssh -o StrictHostKeyChecking=no -p 28960 deploy@173.242.127.125 
    - if [ $(docker ps -aq --filter name=countingdown) ]; then echo "then statement"; else echo "else statement"; fi
  when: manual

